name:                hssh
version:             0.1.0.0
github:              lpeterse/haskell-ssh
license:             MIT
author:              Lars Petersen
maintainer:          info@lars-petersen.net
copyright:           2017 Lars Petersen

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            SSH protocol implementation
description:         Please see the README on Github at <https://github.com/lpeterse/haskell-ssh#readme>

flags:
  demo:
    description: Build server demo executable hssh-demo
    manual:      true
    default:     false

dependencies:
- async
- base >= 4.7 && < 5
- bytestring
- cereal
- containers
- cryptonite
- memory
- stm
- clock
- transformers
- exceptions

library:
  source-dirs: src
  ghc-options: -Wall -fno-warn-orphans

tests:
  hssh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hssh
    - tasty
    - tasty-hunit
    - tasty-quickcheck

executables:
  hssh-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hssh
    - socket
    # when:
    #   - condition: flag(demo)
    #     then:
    #       buildable: true
    #     else:
    #       buildable: false
