name:                hssh
version:             0.1.0.0
github:              lpeterse/haskell-ssh
license:             MIT
author:              Lars Petersen
maintainer:          info@lars-petersen.net
copyright:           2017 Lars Petersen
category:            Network

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            SSH protocol implementation
description:         Please see the README on Github at <https://github.com/lpeterse/haskell-ssh#readme>

flags:
  demo:
    description: Build server demo executable hssh-demo
    manual:      true
    default:     false

dependencies:
- async
- base >= 4.7 && < 5
- bytestring
- cereal
- containers
- cryptonite
- memory
- stm
- data-default

library:
  source-dirs: src
  ghc-options: -Wall -fno-warn-orphans
  exposed-modules:
    - Network.SSH
    - Network.SSH.Server
    - Network.SSH.Client
    - Network.SSH.Internal

tests:
  hssh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hssh
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck

executables:
  hssh-server:
    main:                Main.hs
    source-dirs:         app/hssh-server
    ghc-options:
    - -rtsopts
    dependencies:
    - hssh
    - socket >= 0.8.2.0
  hssh-client:
    main:                Main.hs
    source-dirs:         app/hssh-client
    ghc-options:
    - -rtsopts
    dependencies:
    - hssh
    - socket >= 0.8.2.0
