resolver: lts-12.2
packages:
- .
- ../haskell-socket
#- ../haskell-terminal
#- ../haskell-replique
extra-deps:
  - git: https://github.com/lpeterse/cryptonite
    commit: c616a6762ed30a726c2659072bfbe839c1b70dda
